apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: krwlfws33-nodejs
  janus-idp.io/tekton: krwlfws33-nodejs
  backstage.io/kubernetes-id: krwlfws33-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: krwlfws33-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
